### ISSUE TITLE
feature request: sync - export/import

### ISSUE THREAD

**Issue by pflegende** [rNeomy/addon-manager#4]
Good job!
Great!

would be great to have some sync function or also a export /import utility to transfer extensions between devices
:)

:happy xmas:

**Comment by rNeomy** [comment]
We will have the export and import feature on the options panel on version 0.2.1. The sync is not yet available. The problem is for Chrome to allow altering the extension's state, it requires user action. So it is not possible to update the states automatically in the background script without user action.
